### ISSUE TITLE
Needs updated to the latest signalr-core.

### ISSUE THREAD

**Issue by jbuedel** [thundertecnologia/angular-signalr-core-hub#1]
I'm running into this issue: https://stackoverflow.com/questions/49765667/signalr-no-transport and I pretty sure the culprit is mismatched versions. Would appreciate if you could upgrade this bower package. (The signalr version from my csproj is 1.1.0.) Thanks.

**Comment by fabiogusmao** [comment]
OK I'll update the client and create a branch with the current version and notify you.

We created this package for two projects when SignalR Core was still in preview and never gave it any more love.

**Comment by jbuedel** [comment]
Much appreciated. I'm trying to port my server to asp.net core without doing what might otherwise be a ton of work on the angularjs app.

**Comment by fabiogusmao** [comment]
Hi @jbuedel I've published the update as a new [release](https://github.com/thundertecnologia/angular-signalr-core-hub/releases/tag/1.1.4.0). Please give it a try and report below.

**Comment by jbuedel** [comment]
Hi @fabiogusmao I am using it but am getting the runtime error shown here.
![image](https://user-images.githubusercontent.com/85681/73571330-ed17c400-4433-11ea-86d0-5a37a8ba9bc5.png) 

My understanding of your gulp build is that it should have bundled up the signalR implementation, along with your hub.js code, into a single file and placed that into `dist`. However, it doesn't seem to have done so. (I've never authored a bower package before so take my analysis with a grain of salt.)

**Comment by fabiogusmao** [comment]
@jbuedel ,

your analysis is correct. 

I was certain I saw 2 files listed on the Gulp output yesterday but the SDK wasn't in the distributed file at all :(


I've replaced version `1.1.4.0`with fixed version `1.1.4.1` which has the client SDK included.
![image](https://user-images.githubusercontent.com/2974851/73573739-e2205c00-4452-11ea-9933-6ea940dfafae.png)

Please tell me if this works otherwise I'll build something and look more closely into the matter.

Havent't used SignalR for 2 or so years.

**Comment by fabiogusmao** [comment]
Closing this since we had no response in a week.

**Comment by jbuedel** [comment]
Hello @fabiogusmao . Sorry for the delay in getting back to you. The latest release got me past the last issue. However I got some new errors, and if I recall correctly I think it was due to the `Hub` wrapper not implementing the signalr interface quite right. I ultimately decided to bite the bullet and pull signalr in manually instead of as a bower package. I am now working against the raw signalr interface, and not using this package.

**Comment by fabiogusmao** [comment]
@jbuedel Yes I recomend you do that because this package was developed when SignalR Core was alpha and because I was trying to migrate from another package and as you probably noticed we no longer maintain it since the two projects we built it for are no longer active.
